#define IDD_SETTINGS_MENU                    100010

#define IDC_SETTINGS_MENU_BTN_SKILL          100
#define IDC_SETTINGS_MENU_BTN_NUM            101
#define IDC_SETTINGS_MENU_BTN_HUD_RESET      102
#define IDC_SETTINGS_MENU_BTN_AI_RAIL        103
#define IDC_SETTINGS_MENU_BTN_HUD_LAYOUT     104
#define IDC_SETTINGS_MENU_BTN_HUD_OBJECTS    105
#define IDC_SETTINGS_MENU_BTN_HC_RESPONSE    106