#define IDD_CUSTOM_FORMATION                         100080
#define IDD_CUSTOM_FORMATION_SAVE                    100090
#define IDD_CUSTOM_FORMATION_MANAGE                  100091

// Main custom formation display.
#define IDC_CUSTOM_FORMATION_MOUSE_SURFACE           9

#define IDC_CUSTOM_FORMATION_TEAM_RED                10
#define IDC_CUSTOM_FORMATION_TEAM_GREEN              11
#define IDC_CUSTOM_FORMATION_TEAM_BLUE               12
#define IDC_CUSTOM_FORMATION_TEAM_YELLOW             13
#define IDC_CUSTOM_FORMATION_TEAM_MAIN               14
#define IDC_CUSTOM_FORMATION_TEAM_ALL                15

#define IDC_CUSTOM_FORMATION_ACTIVATION_IMAGE        16
#define IDC_CUSTOM_FORMATION_ACTIVATION_BUTTON       17
#define IDC_CUSTOM_FORMATION_SAVED_LISTBOX           18

// Dynamically created on the main display by fnc_saveButton.
#define IDC_CUSTOM_FORMATION_DYNAMIC_SAVE_NAME_EDIT  20

#define IDC_CUSTOM_FORMATION_CLEAR_BUTTON            21
#define IDC_CUSTOM_FORMATION_SAVE_BUTTON             22
#define IDC_CUSTOM_FORMATION_MANAGE_IMAGE            23
#define IDC_CUSTOM_FORMATION_MANAGE_BUTTON           24

// Saved-formation management display.
#define IDC_CUSTOM_FORMATION_MANAGE_CLOSE_BUTTON     30
#define IDC_CUSTOM_FORMATION_MANAGE_SELECT_ALL       31
#define IDC_CUSTOM_FORMATION_MANAGE_SELECTED_COUNT   32
#define IDC_CUSTOM_FORMATION_MANAGE_TRASH_IMAGE      33
#define IDC_CUSTOM_FORMATION_MANAGE_TRASH_BUTTON     34
#define IDC_CUSTOM_FORMATION_MANAGE_ROWS_GROUP       35
#define IDC_CUSTOM_FORMATION_MANAGE_EMPTY_TEXT       36

#define IDC_CUSTOM_FORMATION_MANAGE_CONFIRM_TEXT     37
#define IDC_CUSTOM_FORMATION_MANAGE_CONFIRM_CANCEL   38
#define IDC_CUSTOM_FORMATION_MANAGE_CONFIRM_DELETE   39

// Separate legacy save display.
#define IDC_CUSTOM_FORMATION_SAVE_NAME_EDIT          10
#define IDC_CUSTOM_FORMATION_SAVE_CONFIRM_BUTTON     11
#define IDC_CUSTOM_FORMATION_SAVE_CANCEL_BUTTON      12

// Dynamically created formation-grid pictures use this IDC and increment upward.
#define IDC_CUSTOM_FORMATION_GRID_START              101