#include "..\script_component.hpp"
#include "..\dialog_defines.hpp"

private _display = uiNamespace getVariable [QGVAR(display), displayNull];
if (isNull _display) exitWith {};

private _controls = createHashMapFromArray [
    ["inputCapture", _display displayCtrl IDC_MAP_INPUT_CAPTURE],
    ["inputBlocker", _display displayCtrl IDC_MAP_INPUT_BLOCKER],

    ["ufsbBackground", _display displayCtrl IDC_MAP_UFSB_BACKGROUND],
    ["ufsbFrame", _display displayCtrl IDC_MAP_UFSB_FRAME],

    ["topExtrasBackground", _display displayCtrl IDC_MAP_TOP_EXTRAS_BACKGROUND],
    ["topExtrasFrame", _display displayCtrl IDC_MAP_TOP_EXTRAS_FRAME],
    ["topRefreshImg", _display displayCtrl IDC_MAP_TOP_REFRESH_IMG],
    ["topRefreshBtn", _display displayCtrl IDC_MAP_TOP_REFRESH_BTN],
    ["topDisbandImg", _display displayCtrl IDC_MAP_TOP_DISBAND_IMG],
    ["topDisbandBtn", _display displayCtrl IDC_MAP_TOP_DISBAND_BTN],
    ["topToggleTrackerImg", _display displayCtrl IDC_MAP_TOP_TOGGLETRACKER_IMG],
    ["topToggleTrackerBtn", _display displayCtrl IDC_MAP_TOP_TOGGLETRACKER_BTN],

    ["ufsbStanceTravelImg", _display displayCtrl IDC_MAP_UFSB_STANCE_TRAVEL_IMG],
    ["ufsbStanceTravelBtn", _display displayCtrl IDC_MAP_UFSB_STANCE_TRAVEL_BTN],
    ["ufsbWpSpeedImg", _display displayCtrl IDC_MAP_UFSB_WP_SPEED_IMG],
    ["ufsbWpSpeedBtn", _display displayCtrl IDC_MAP_UFSB_WP_SPEED_BTN],
    ["ufsbStanceArrivalImg", _display displayCtrl IDC_MAP_UFSB_STANCE_ARRIVAL_IMG],
    ["ufsbStanceArrivalBtn", _display displayCtrl IDC_MAP_UFSB_STANCE_ARRIVAL_BTN],
    ["ufsbCombatModeImg", _display displayCtrl IDC_MAP_UFSB_COMBATMODE_IMG],
    ["ufsbCombatModeBtn", _display displayCtrl IDC_MAP_UFSB_COMBATMODE_BTN],
    ["ufsbWpActionImg", _display displayCtrl IDC_MAP_UFSB_WPACTION_IMG],
    ["ufsbWpActionBtn", _display displayCtrl IDC_MAP_UFSB_WPACTION_BTN],
    ["ufsbWpFormationImg", _display displayCtrl IDC_MAP_UFSB_WPFORMATION_IMG],
    ["ufsbWpFormationBtn", _display displayCtrl IDC_MAP_UFSB_WPFORMATION_BTN],
    ["ufsbSpacing", _display displayCtrl IDC_MAP_UFSB_SPACING],
    ["ufsbWpConditionImg", _display displayCtrl IDC_MAP_UFSB_WPCONDITION_IMG],
    ["ufsbWpConditionBtn", _display displayCtrl IDC_MAP_UFSB_WPCONDITION_BTN],
    ["ufsbTimeoutPopup", _display displayCtrl IDC_MAP_UFSB_TIMEOUT_POPUP],
    ["ufsbUndoImg", _display displayCtrl IDC_MAP_UFSB_UNDO_IMG],
    ["ufsbUndoBtn", _display displayCtrl IDC_MAP_UFSB_UNDO_BTN],
    ["ufsbCancelImg", _display displayCtrl IDC_MAP_UFSB_CANCEL_IMG],
    ["ufsbCancelBtn", _display displayCtrl IDC_MAP_UFSB_CANCEL_BTN],
    ["ufsbHoldImg", _display displayCtrl IDC_MAP_UFSB_HOLD_IMG],
    ["ufsbHoldBtn", _display displayCtrl IDC_MAP_UFSB_HOLD_BTN],
    ["ufsbContinueImg", _display displayCtrl IDC_MAP_UFSB_CONTINUE_IMG],
    ["ufsbContinueBtn", _display displayCtrl IDC_MAP_UFSB_CONTINUE_BTN],

    ["ufsbCommitAll", _display displayCtrl IDC_MAP_UFSB_CommitAll],
    ["ufsbCommitSelected", _display displayCtrl IDC_MAP_UFSB_CommitSelected],
    ["ufsbExit", _display displayCtrl IDC_MAP_UFSB_Exit],

    ["ufsbSubselection01Bg", _display displayCtrl IDC_MAP_UFSB_Subselection_01_BG],
    ["ufsbSubselection02Bg", _display displayCtrl IDC_MAP_UFSB_Subselection_02_BG],

    ["ufsbSubselection01Parent", _display displayCtrl IDC_MAP_UFSB_Subselection_01_Parent],
    ["ufsbSubselection01Img01", _display displayCtrl IDC_MAP_UFSB_Subselection_01_IMG_01],
    ["ufsbSubselection01Btn01", _display displayCtrl IDC_MAP_UFSB_Subselection_01_BTN_01],
    ["ufsbSubselection01Img02", _display displayCtrl IDC_MAP_UFSB_Subselection_01_IMG_02],
    ["ufsbSubselection01Btn02", _display displayCtrl IDC_MAP_UFSB_Subselection_01_BTN_02],
    ["ufsbSubselection01Img03", _display displayCtrl IDC_MAP_UFSB_Subselection_01_IMG_03],
    ["ufsbSubselection01Btn03", _display displayCtrl IDC_MAP_UFSB_Subselection_01_BTN_03],
    ["ufsbSubselection01Img04", _display displayCtrl IDC_MAP_UFSB_Subselection_01_IMG_04],
    ["ufsbSubselection01Btn04", _display displayCtrl IDC_MAP_UFSB_Subselection_01_BTN_04],
    ["ufsbSubselection01Img05", _display displayCtrl IDC_MAP_UFSB_Subselection_01_IMG_05],
    ["ufsbSubselection01Btn05", _display displayCtrl IDC_MAP_UFSB_Subselection_01_BTN_05],
    ["ufsbSubselection01Img06", _display displayCtrl IDC_MAP_UFSB_Subselection_01_IMG_06],
    ["ufsbSubselection01Btn06", _display displayCtrl IDC_MAP_UFSB_Subselection_01_BTN_06],
    ["ufsbSubselection01Img07", _display displayCtrl IDC_MAP_UFSB_Subselection_01_IMG_07],
    ["ufsbSubselection01Btn07", _display displayCtrl IDC_MAP_UFSB_Subselection_01_BTN_07],
    ["ufsbSubselection01Img08", _display displayCtrl IDC_MAP_UFSB_Subselection_01_IMG_08],
    ["ufsbSubselection01Btn08", _display displayCtrl IDC_MAP_UFSB_Subselection_01_BTN_08],
    ["ufsbSubselection01Img09", _display displayCtrl IDC_MAP_UFSB_Subselection_01_IMG_09],
    ["ufsbSubselection01Btn09", _display displayCtrl IDC_MAP_UFSB_Subselection_01_BTN_09],
    ["ufsbSubselection01Img10", _display displayCtrl IDC_MAP_UFSB_Subselection_01_IMG_10],
    ["ufsbSubselection01Btn10", _display displayCtrl IDC_MAP_UFSB_Subselection_01_BTN_10],

    ["ufsbSubselection02Parent", _display displayCtrl IDC_MAP_UFSB_Subselection_02_Parent],
    ["ufsbSubselection02Img01", _display displayCtrl IDC_MAP_UFSB_Subselection_02_IMG_01],
    ["ufsbSubselection02Btn01", _display displayCtrl IDC_MAP_UFSB_Subselection_02_BTN_01],
    ["ufsbSubselection02Img02", _display displayCtrl IDC_MAP_UFSB_Subselection_02_IMG_02],
    ["ufsbSubselection02Btn02", _display displayCtrl IDC_MAP_UFSB_Subselection_02_BTN_02],
    ["ufsbSubselection02Img03", _display displayCtrl IDC_MAP_UFSB_Subselection_02_IMG_03],
    ["ufsbSubselection02Btn03", _display displayCtrl IDC_MAP_UFSB_Subselection_02_BTN_03],
    ["ufsbSubselection02Img04", _display displayCtrl IDC_MAP_UFSB_Subselection_02_IMG_04],
    ["ufsbSubselection02Btn04", _display displayCtrl IDC_MAP_UFSB_Subselection_02_BTN_04],
    ["ufsbSubselection02Img05", _display displayCtrl IDC_MAP_UFSB_Subselection_02_IMG_05],
    ["ufsbSubselection02Btn05", _display displayCtrl IDC_MAP_UFSB_Subselection_02_BTN_05],
    ["ufsbSubselection02Img06", _display displayCtrl IDC_MAP_UFSB_Subselection_02_IMG_06],
    ["ufsbSubselection02Btn06", _display displayCtrl IDC_MAP_UFSB_Subselection_02_BTN_06],
    ["ufsbSubselection02Img07", _display displayCtrl IDC_MAP_UFSB_Subselection_02_IMG_07],
    ["ufsbSubselection02Btn07", _display displayCtrl IDC_MAP_UFSB_Subselection_02_BTN_07],
    ["ufsbSubselection02Img08", _display displayCtrl IDC_MAP_UFSB_Subselection_02_IMG_08],
    ["ufsbSubselection02Btn08", _display displayCtrl IDC_MAP_UFSB_Subselection_02_BTN_08],
    ["ufsbSubselection02Img09", _display displayCtrl IDC_MAP_UFSB_Subselection_02_IMG_09],
    ["ufsbSubselection02Btn09", _display displayCtrl IDC_MAP_UFSB_Subselection_02_BTN_09],
    ["ufsbSubselection02Img10", _display displayCtrl IDC_MAP_UFSB_Subselection_02_IMG_10],
    ["ufsbSubselection02Btn10", _display displayCtrl IDC_MAP_UFSB_Subselection_02_BTN_10],

    ["hcgpStartupBar", _display displayCtrl IDC_MAP_HCGP_STARTUP_BAR],
    ["hcgpStartupText", _display displayCtrl IDC_MAP_HCGP_STARTUP_TEXT],
    ["hcgpParent", _display displayCtrl IDC_MAP_HCGP_Parent],

    ["hcgpStanceAutoImg", _display displayCtrl IDC_MAP_HCGP_STANCES_AUTO_IMG],
    ["hcgpStanceStandImg", _display displayCtrl IDC_MAP_HCGP_STANCES_STAND_IMG],
    ["hcgpStanceCrouchImg", _display displayCtrl IDC_MAP_HCGP_STANCES_CROUCH_IMG],
    ["hcgpStanceProneImg", _display displayCtrl IDC_MAP_HCGP_STANCES_PRONE_IMG],

    ["hcgpListboxBehaviour", _display displayCtrl IDC_MAP_HCGP_LISTBOX_BEHAVIOUR],
    ["hcgpListboxCombatMode", _display displayCtrl IDC_MAP_HCGP_LISTBOX_COMBATMODE],
    ["hcgpListboxFormation", _display displayCtrl IDC_MAP_HCGP_LISTBOX_FORMATION],
    ["hcgpListboxTeamColor", _display displayCtrl IDC_MAP_HCGP_LISTBOX_TEAMCOLOR],

    ["hcgpConfirmBg", _display displayCtrl IDC_MAP_HCGP_CONFIRM_BG],
    ["hcgpConfirmBtn", _display displayCtrl IDC_MAP_HCGP_CONFIRM_BTN],
    ["hcgpCancelBg", _display displayCtrl IDC_MAP_HCGP_CANCEL_BG],
    ["hcgpCancelBtn", _display displayCtrl IDC_MAP_HCGP_CANCEL_BTN],

    ["hcgpActionMacro0Bg", _display displayCtrl IDC_MAP_HCGP_ActionMacro_0_BG],
    ["hcgpActionMacro0Img", _display displayCtrl IDC_MAP_HCGP_ActionMacro_0_IMG],
    ["hcgpActionMacro0Btn", _display displayCtrl IDC_MAP_HCGP_ActionMacro_0_BTN],
    ["hcgpActionMacro1Bg", _display displayCtrl IDC_MAP_HCGP_ActionMacro_1_BG],
    ["hcgpActionMacro1Img", _display displayCtrl IDC_MAP_HCGP_ActionMacro_1_IMG],
    ["hcgpActionMacro1Btn", _display displayCtrl IDC_MAP_HCGP_ActionMacro_1_BTN],
    ["hcgpActionMacro2Bg", _display displayCtrl IDC_MAP_HCGP_ActionMacro_2_BG],
    ["hcgpActionMacro2Img", _display displayCtrl IDC_MAP_HCGP_ActionMacro_2_IMG],
    ["hcgpActionMacro2Btn", _display displayCtrl IDC_MAP_HCGP_ActionMacro_2_BTN],
    ["hcgpActionMacro3Bg", _display displayCtrl IDC_MAP_HCGP_ActionMacro_3_BG],
    ["hcgpActionMacro3Img", _display displayCtrl IDC_MAP_HCGP_ActionMacro_3_IMG],
    ["hcgpActionMacro3Btn", _display displayCtrl IDC_MAP_HCGP_ActionMacro_3_BTN],
    ["hcgpActionMacro4Bg", _display displayCtrl IDC_MAP_HCGP_ActionMacro_4_BG],
    ["hcgpActionMacro4Img", _display displayCtrl IDC_MAP_HCGP_ActionMacro_4_IMG],
    ["hcgpActionMacro4Btn", _display displayCtrl IDC_MAP_HCGP_ActionMacro_4_BTN],
    ["hcgpActionMacro5Bg", _display displayCtrl IDC_MAP_HCGP_ActionMacro_5_BG],
    ["hcgpActionMacro5Img", _display displayCtrl IDC_MAP_HCGP_ActionMacro_5_IMG],
    ["hcgpActionMacro5Btn", _display displayCtrl IDC_MAP_HCGP_ActionMacro_5_BTN],
    ["hcgpActionMacro6Bg", _display displayCtrl IDC_MAP_HCGP_ActionMacro_6_BG],
    ["hcgpActionMacro6Img", _display displayCtrl IDC_MAP_HCGP_ActionMacro_6_IMG],
    ["hcgpActionMacro6Btn", _display displayCtrl IDC_MAP_HCGP_ActionMacro_6_BTN],
    ["hcgpActionMacro7Bg", _display displayCtrl IDC_MAP_HCGP_ActionMacro_7_BG],
    ["hcgpActionMacro7Img", _display displayCtrl IDC_MAP_HCGP_ActionMacro_7_IMG],
    ["hcgpActionMacro7Btn", _display displayCtrl IDC_MAP_HCGP_ActionMacro_7_BTN],
    ["hcgpActionMacro8Bg", _display displayCtrl IDC_MAP_HCGP_ActionMacro_8_BG],
    ["hcgpActionMacro8Img", _display displayCtrl IDC_MAP_HCGP_ActionMacro_8_IMG],
    ["hcgpActionMacro8Btn", _display displayCtrl IDC_MAP_HCGP_ActionMacro_8_BTN],
    ["hcgpActionMacro9Bg", _display displayCtrl IDC_MAP_HCGP_ActionMacro_9_BG],
    ["hcgpActionMacro9Img", _display displayCtrl IDC_MAP_HCGP_ActionMacro_9_IMG],
    ["hcgpActionMacro9Btn", _display displayCtrl IDC_MAP_HCGP_ActionMacro_9_BTN],

    ["hcwpParent", _display displayCtrl IDC_MAP_HCGP_WP_Parent],
    ["hcwpGroupNameBg", _display displayCtrl IDC_MAP_HCGP_GROUPNAME_BG],
    ["hcwpGroupNameText", _display displayCtrl IDC_MAP_HCGP_GROUPNAME_TXT],
    ["hcwpBehaviourCombo", _display displayCtrl IDC_MAP_HCWP_Behaviour_Combo],
    ["hcwpCombatModeCombo", _display displayCtrl IDC_MAP_HCWP_CombatMode_Combo],
    ["hcwpSpeedCombo", _display displayCtrl IDC_MAP_HCWP_Speed_Combo],
    ["hcwpFormationCombo", _display displayCtrl IDC_MAP_HCWP_Formation_Combo],
    ["hcwpCompletionParent", _display displayCtrl IDC_MAP_HCWP_Completion_Parent],
    ["hcwpCompletionHeaderText", _display displayCtrl IDC_MAP_HCWP_Completion_Header_TXT],
    ["hcwpConditionPreType", _display displayCtrl IDC_MAP_HCWP_Condition_Pre_Type],
    ["hcwpConditionPreMode", _display displayCtrl IDC_MAP_HCWP_Condition_Pre_Mode],
    ["hcwpTypeParent", _display displayCtrl IDC_MAP_HCWP_Type_Parent],
    ["hcwpTypeAction", _display displayCtrl IDC_MAP_HCWP_Type_Action],
    ["hcwpActionParentMain", _display displayCtrl IDC_MAP_HCWP_Action_Parent_MAIN],
    ["hcwpActionFormationCombo", _display displayCtrl IDC_MAP_HCWP_Action_Formation_Combo],
    ["hcwpConditionPostType", _display displayCtrl IDC_MAP_HCWP_Condition_Post_Type],
    ["hcwpConditionPostMode", _display displayCtrl IDC_MAP_HCWP_Condition_Post_Mode],
    ["hcwpActionParentAdd", _display displayCtrl IDC_MAP_HCWP_Action_Parent_ADD],
    ["hcwpActionAddFormationText", _display displayCtrl IDC_MAP_HCWP_Action_Add_Formation_TXT],
    ["hcwpActionAddFormationCombo", _display displayCtrl IDC_MAP_HCWP_Action_Add_Formation_Combo],
    ["hcwpActionAddCompletionText", _display displayCtrl IDC_MAP_HCWP_Action_Add_Completion_TXT],
    ["hcwpActionAddCompletionCombo", _display displayCtrl IDC_MAP_HCWP_Action_Add_Completion_Combo],
    ["hcwpConfirmBg", _display displayCtrl IDC_MAP_HCWP_Confirm_BG],
    ["hcwpConfirmText", _display displayCtrl IDC_MAP_HCWP_Confirm_TEXT],
    ["hcwpDeleteBg", _display displayCtrl IDC_MAP_HCWP_Delete_BG],
    ["hcwpDeleteText", _display displayCtrl IDC_MAP_HCWP_Delete_TEXT],

    ["sqwpControlsGroup", _display displayCtrl IDC_MAP_SQWP_ControlsGroup],
    ["sqwpSpeedImg", _display displayCtrl IDC_MAP_SQWP_Speed_IMG],
    ["sqwpSpeedBtn", _display displayCtrl IDC_MAP_SQWP_Speed_BTN],
    ["sqwpStanceTravelImg", _display displayCtrl IDC_MAP_SQWP_Stance_Travel_IMG],
    ["sqwpStanceTravelBtn", _display displayCtrl IDC_MAP_SQWP_Stance_Travel_BTN],
    ["sqwpCombo", _display displayCtrl IDC_MAP_SQWP_Combo],
    ["sqwpStanceArrivalImg", _display displayCtrl IDC_MAP_SQWP_Stance_Arrival_IMG],
    ["sqwpStanceArrivalBtn", _display displayCtrl IDC_MAP_SQWP_Stance_Arrival_BTN],
    ["sqwpDeleteImg", _display displayCtrl IDC_MAP_SQWP_Delete_IMG],
    ["sqwpDeleteBtn", _display displayCtrl IDC_MAP_SQWP_Delete_BTN],

    ["goCodeBg", _display displayCtrl IDC_MAP_Order_GoCode_BG],
    ["goCodeAImg", _display displayCtrl IDC_MAP_Order_GoCode_A_IMG],
    ["goCodeABtn", _display displayCtrl IDC_MAP_Order_GoCode_A_BTN],
    ["goCodeBImg", _display displayCtrl IDC_MAP_Order_GoCode_B_IMG],
    ["goCodeBBtn", _display displayCtrl IDC_MAP_Order_GoCode_B_BTN],
    ["goCodeCImg", _display displayCtrl IDC_MAP_Order_GoCode_C_IMG],
    ["goCodeCBtn", _display displayCtrl IDC_MAP_Order_GoCode_C_BTN],
    ["goCodeDImg", _display displayCtrl IDC_MAP_Order_GoCode_D_IMG],
    ["goCodeDBtn", _display displayCtrl IDC_MAP_Order_GoCode_D_BTN],
    ["dirMousePosToPlayerPosText", _display displayCtrl IDC_MAP_Dir_MousePosToPlayerPos_TXT],

    ["dynamicCombo", _display displayCtrl IDC_MAP_DynamicCombo]
];

uiNamespace setVariable [QGVAR(controls), _controls];