#include "..\script_component.hpp"
#include "..\dialog_defines.hpp"

private _display = uiNamespace getVariable [QGVAR(display), displayNull];
if (isNull _display) exitWith {};

private _controls = createHashMapFromArray [
    ["bgCore", _display displayCtrl IDC_RADIAL_BG_CORE],
    ["bgTop", _display displayCtrl IDC_RADIAL_BG_TOP],
    ["bgRight", _display displayCtrl IDC_RADIAL_BG_RIGHT],
    ["bgBottom", _display displayCtrl IDC_RADIAL_BG_BOTTOM],
    ["bgLeft", _display displayCtrl IDC_RADIAL_BG_LEFT],

    ["coreRefreshDataImg", _display displayCtrl IDC_RADIAL_CORE_REFRESHDATA_IMG],
    ["coreRefreshDataBtn", _display displayCtrl IDC_RADIAL_CORE_REFRESHDATA_BTN],

    ["innerActionsImg", _display displayCtrl IDC_RADIAL_INNERRING_ACTIONS_IMG],
    ["innerActionsBtn", _display displayCtrl IDC_RADIAL_INNERRING_ACTIONS_BTN],
    ["innerRoeImg", _display displayCtrl IDC_RADIAL_INNERRING_ROE_IMG],
    ["innerRoeBtn", _display displayCtrl IDC_RADIAL_INNERRING_ROE_BTN],
    ["innerAutoImg", _display displayCtrl IDC_RADIAL_INNERRING_AUTO_IMG],
    ["innerAutoBtn", _display displayCtrl IDC_RADIAL_INNERRING_AUTO_BTN],
    ["innerStancesImg", _display displayCtrl IDC_RADIAL_INNERRING_STANCES_IMG],
    ["innerStancesBtn", _display displayCtrl IDC_RADIAL_INNERRING_STANCES_BTN],
    ["innerItemsImg", _display displayCtrl IDC_RADIAL_INNERRING_ITEMS_IMG],
    ["innerItemsBtn", _display displayCtrl IDC_RADIAL_INNERRING_ITEMS_BTN],
    ["innerVehiclesImg", _display displayCtrl IDC_RADIAL_INNERRING_VEHICLES_IMG],
    ["innerVehiclesBtn", _display displayCtrl IDC_RADIAL_INNERRING_VEHICLES_BTN],
    ["innerFormationImg", _display displayCtrl IDC_RADIAL_INNERRING_FORMATION_IMG],
    ["innerFormationBtn", _display displayCtrl IDC_RADIAL_INNERRING_FORMATION_BTN],
    ["innerGrenadesImg", _display displayCtrl IDC_RADIAL_INNERRING_GRENADES_IMG],
    ["innerGrenadesBtn", _display displayCtrl IDC_RADIAL_INNERRING_GRENADES_BTN],

    ["outerTop1Img", _display displayCtrl IDC_RADIAL_OUTERTOP_1_IMG],
    ["outerTop1Btn", _display displayCtrl IDC_RADIAL_OUTERTOP_1_BTN],
    ["outerTop2Img", _display displayCtrl IDC_RADIAL_OUTERTOP_2_IMG],
    ["outerTop2Btn", _display displayCtrl IDC_RADIAL_OUTERTOP_2_BTN],
    ["outerTop3Img", _display displayCtrl IDC_RADIAL_OUTERTOP_3_IMG],
    ["outerTop3Btn", _display displayCtrl IDC_RADIAL_OUTERTOP_3_BTN],
    ["outerTop4Img", _display displayCtrl IDC_RADIAL_OUTERTOP_4_IMG],
    ["outerTop4Btn", _display displayCtrl IDC_RADIAL_OUTERTOP_4_BTN],

    ["outerRight1Img", _display displayCtrl IDC_RADIAL_OUTERRIGHT_1_IMG],
    ["outerRight1Btn", _display displayCtrl IDC_RADIAL_OUTERRIGHT_1_BTN],
    ["outerRight2Img", _display displayCtrl IDC_RADIAL_OUTERRIGHT_2_IMG],
    ["outerRight2Btn", _display displayCtrl IDC_RADIAL_OUTERRIGHT_2_BTN],
    ["outerRight3Img", _display displayCtrl IDC_RADIAL_OUTERRIGHT_3_IMG],
    ["outerRight3Btn", _display displayCtrl IDC_RADIAL_OUTERRIGHT_3_BTN],
    ["outerRight4Img", _display displayCtrl IDC_RADIAL_OUTERRIGHT_4_IMG],
    ["outerRight4Btn", _display displayCtrl IDC_RADIAL_OUTERRIGHT_4_BTN],

    ["outerBottom1Img", _display displayCtrl IDC_RADIAL_OUTERBOTTOM_1_IMG],
    ["outerBottom1Btn", _display displayCtrl IDC_RADIAL_OUTERBOTTOM_1_BTN],
    ["outerBottom2Img", _display displayCtrl IDC_RADIAL_OUTERBOTTOM_2_IMG],
    ["outerBottom2Btn", _display displayCtrl IDC_RADIAL_OUTERBOTTOM_2_BTN],
    ["outerBottom3Img", _display displayCtrl IDC_RADIAL_OUTERBOTTOM_3_IMG],
    ["outerBottom3Btn", _display displayCtrl IDC_RADIAL_OUTERBOTTOM_3_BTN],
    ["outerBottom4Img", _display displayCtrl IDC_RADIAL_OUTERBOTTOM_4_IMG],
    ["outerBottom4Btn", _display displayCtrl IDC_RADIAL_OUTERBOTTOM_4_BTN],

    ["outerLeft1Img", _display displayCtrl IDC_RADIAL_OUTERLEFT_1_IMG],
    ["outerLeft1Btn", _display displayCtrl IDC_RADIAL_OUTERLEFT_1_BTN],
    ["outerLeft2Img", _display displayCtrl IDC_RADIAL_OUTERLEFT_2_IMG],
    ["outerLeft2Btn", _display displayCtrl IDC_RADIAL_OUTERLEFT_2_BTN],
    ["outerLeft3Img", _display displayCtrl IDC_RADIAL_OUTERLEFT_3_IMG],
    ["outerLeft3Btn", _display displayCtrl IDC_RADIAL_OUTERLEFT_3_BTN],
    ["outerLeft4Img", _display displayCtrl IDC_RADIAL_OUTERLEFT_4_IMG],
    ["outerLeft4Btn", _display displayCtrl IDC_RADIAL_OUTERLEFT_4_BTN],

    ["extensionRightBackground", _display displayCtrl IDC_RADIAL_EXTENSIONRIGHT_BACKGROUND],
    ["extensionRightLbSourcesHeader", _display displayCtrl IDC_RADIAL_EXTENSIONRIGHT_LBSOURCES_HEADER],
    ["extensionRightLbSourcesBox", _display displayCtrl IDC_RADIAL_EXTENSIONRIGHT_LBSOURCES_BOX],
    ["extensionRightLbSubselHeader", _display displayCtrl IDC_RADIAL_EXTENSIONRIGHT_LBSUBSEL_HEADER],
    ["extensionRightLbSubselBox", _display displayCtrl IDC_RADIAL_EXTENSIONRIGHT_LBSUBSEL_BOX],
    ["extensionRightGoBtn", _display displayCtrl IDC_RADIAL_EXTENSIONRIGHT_GO_BTN],

    ["dashboardParent", _display displayCtrl IDC_RADIAL_DASHBOARD_PARENT],
    ["dashboardBg", _display displayCtrl IDC_RADIAL_DASHBOARD_BG],
    ["dashboardGroupName", _display displayCtrl IDC_RADIAL_DASHBOARD_GROUPNAME],
    ["dashboardGroupIcon", _display displayCtrl IDC_RADIAL_DASHBOARD_GROUPICON],
    ["dashboardTxtUnitSize", _display displayCtrl IDC_RADIAL_DASHBOARD_TXT_UNITSIZE],
    ["dashboardTxtLocation", _display displayCtrl IDC_RADIAL_DASHBOARD_TXT_LOCATION],
    ["dashboardTxtTask", _display displayCtrl IDC_RADIAL_DASHBOARD_TXT_TASK],
    ["dashboardPgBarsBg", _display displayCtrl IDC_RADIAL_DASHBOARD_PGBARS_BG],
    ["dashboardPgHealthTxt", _display displayCtrl IDC_RADIAL_DASHBOARD_PG_HEALTH_TXT],
    ["dashboardPgHealthBar", _display displayCtrl IDC_RADIAL_DASHBOARD_PG_HEALTH_BAR],
    ["dashboardPgRosterTxt", _display displayCtrl IDC_RADIAL_DASHBOARD_PG_ROSTER_TXT],
    ["dashboardPgRosterStructured", _display displayCtrl IDC_RADIAL_DASHBOARD_PG_ROSTER_STRUCTURED],

    ["extensionLeftRevealer", _display displayCtrl IDC_RADIAL_EXTENSIONLEFT_REVEALER],
    ["extensionLeftHider", _display displayCtrl IDC_RADIAL_EXTENSIONLEFT_HIDER],
    ["extensionLeftBg", _display displayCtrl IDC_RADIAL_EXTENSIONLEFT_BG],
    ["extensionLeftCtrlsGroup", _display displayCtrl IDC_RADIAL_EXTENSIONLEFT_CTRLSGROUP],
    ["extensionLeftHoldImg", _display displayCtrl IDC_RADIAL_EXTENSIONLEFT_HOLD_IMG],
    ["extensionLeftHoldBtn", _display displayCtrl IDC_RADIAL_EXTENSIONLEFT_HOLD_BTN],
    ["extensionLeftContinueImg", _display displayCtrl IDC_RADIAL_EXTENSIONLEFT_CONTINUE_IMG],
    ["extensionLeftContinueBtn", _display displayCtrl IDC_RADIAL_EXTENSIONLEFT_CONTINUE_BTN],
    ["extensionLeftTeamColorBg", _display displayCtrl IDC_RADIAL_EXTENSIONLEFT_TEAMCOLOR_BG],
    ["extensionLeftTeamColorFrame", _display displayCtrl IDC_RADIAL_EXTENSIONLEFT_TEAMCOLOR_FRAME],
    ["extensionLeftTree", _display displayCtrl IDC_RADIAL_EXTENSIONLEFT_TREE],
    ["extensionLeftTcboxRedImg", _display displayCtrl IDC_RADIAL_EXTENSIONLEFT_TCBOX_RED_IMG],
    ["extensionLeftTcboxRedBtn", _display displayCtrl IDC_RADIAL_EXTENSIONLEFT_TCBOX_RED_BTN],
    ["extensionLeftTcboxGreenImg", _display displayCtrl IDC_RADIAL_EXTENSIONLEFT_TCBOX_GREEN_IMG],
    ["extensionLeftTcboxGreenBtn", _display displayCtrl IDC_RADIAL_EXTENSIONLEFT_TCBOX_GREEN_BTN],
    ["extensionLeftTcboxBlueImg", _display displayCtrl IDC_RADIAL_EXTENSIONLEFT_TCBOX_BLUE_IMG],
    ["extensionLeftTcboxBlueBtn", _display displayCtrl IDC_RADIAL_EXTENSIONLEFT_TCBOX_BLUE_BTN],
    ["extensionLeftTcboxYellowImg", _display displayCtrl IDC_RADIAL_EXTENSIONLEFT_TCBOX_YELLOW_IMG],
    ["extensionLeftTcboxYellowBtn", _display displayCtrl IDC_RADIAL_EXTENSIONLEFT_TCBOX_YELLOW_BTN],
    ["extensionLeftTcboxWhiteImg", _display displayCtrl IDC_RADIAL_EXTENSIONLEFT_TCBOX_WHITE_IMG],
    ["extensionLeftTcboxWhiteBtn", _display displayCtrl IDC_RADIAL_EXTENSIONLEFT_TCBOX_WHITE_BTN],
    ["extensionLeftTcboxPurpleImg", _display displayCtrl IDC_RADIAL_EXTENSIONLEFT_TCBOX_PURPLE_IMG],
    ["extensionLeftTcboxPurpleBtn", _display displayCtrl IDC_RADIAL_EXTENSIONLEFT_TCBOX_PURPLE_BTN],
    ["extensionLeftTcBox", _display displayCtrl IDC_RADIAL_EXTENSIONLEFT_TC_BOX]
];

uiNamespace setVariable [QGVAR(controls), _controls];