#define IDD_SUPPRESSION_AREA_DRAW                         100070

#define IDC_SUPPRESSION_AREA_DRAW_BOX                     3
#define IDC_SUPPRESSION_AREA_ALIBI_BOX                    2
#define IDC_SUPPRESSION_AREA_CONTROL_FRAME                11

#define IDC_SUPPRESSION_AREA_SETTINGS_PARENT              2300

#define IDC_SUPPRESSION_AREA_TYPE_PIC_UNLIMITED           1200
#define IDC_SUPPRESSION_AREA_TYPE_PIC_PERCENTAGE          1201
#define IDC_SUPPRESSION_AREA_TYPE_PIC_MAGAZINE            1202
#define IDC_SUPPRESSION_AREA_TYPE_PIC_TIME                1203

#define IDC_SUPPRESSION_AREA_BTN_UNLIMITED                1600
#define IDC_SUPPRESSION_AREA_BTN_PERCENTAGE               1601
#define IDC_SUPPRESSION_AREA_BTN_MAGAZINE                 1602
#define IDC_SUPPRESSION_AREA_BTN_TIME                     1603

#define IDC_SUPPRESSION_AREA_TEXT_UNLIMITED               1001
#define IDC_SUPPRESSION_AREA_TEXT_PERCENTAGE              1002
#define IDC_SUPPRESSION_AREA_TEXT_MAGAZINES               1003
#define IDC_SUPPRESSION_AREA_TEXT_TIME                    1004

#define IDC_SUPPRESSION_AREA_EDIT_PERCENTAGE              1401
#define IDC_SUPPRESSION_AREA_EDIT_MAGAZINES               1402
#define IDC_SUPPRESSION_AREA_EDIT_TIME                    1403

#define IDC_SUPPRESSION_AREA_BTN_CONFIRM                  1604
#define IDC_SUPPRESSION_AREA_BTN_CANCEL                   1605

